// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    CarbonCheckmarkOutlineWarning: typeof import('~icons/carbon/checkmark-outline-warning')['default']
    CarbonDocumentExport: typeof import('~icons/carbon/document-export')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    FluentAddCircle24Regular: typeof import('~icons/fluent/add-circle24-regular')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    HelloApi: typeof import('./components/HelloApi.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IcRoundAutoAwesomeMosaic: typeof import('~icons/ic/round-auto-awesome-mosaic')['default']
    IcRoundSettingsInputComponent: typeof import('~icons/ic/round-settings-input-component')['default']
    LineMdIconify2: typeof import('~icons/line-md/iconify2')['default']
    LogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    LogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    LogosVitejs: typeof import('~icons/logos/vitejs')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    MdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    MdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    MdiCached: typeof import('~icons/mdi/cached')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiCheckboxBlankCircleOutline: typeof import('~icons/mdi/checkbox-blank-circle-outline')['default']
    MdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    MdiCodeTags: typeof import('~icons/mdi/code-tags')['default']
    MdiCurrencyUsd: typeof import('~icons/mdi/currency-usd')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiShieldAccount: typeof import('~icons/mdi/shield-account')['default']
    MdiShieldLockOutline: typeof import('~icons/mdi/shield-lock-outline')['default']
    MdiSquareEditOutline: typeof import('~icons/mdi/square-edit-outline')['default']
    MdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NotoPineapple: typeof import('~icons/noto/pineapple')['default']
    OcticonCpu16: typeof import('~icons/octicon/cpu16')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    SimpleIconsCodeclimate: typeof import('~icons/simple-icons/codeclimate')['default']
    SimpleIconsMarkdown: typeof import('~icons/simple-icons/markdown')['default']
    SrcLink: typeof import('./components/SrcLink.vue')['default']
  }
}
